### ISSUE TITLE
Invalid MCP Server instantiation fails poorly

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/ai#96]
I was attempting to run a MCP server incorrectly. It exited with an error message. This error message was not surfaced by the MCP Client sample code.

```console
$ dart run bin/mcp_client.dart
connecting to server
server started
initializing server
Unhandled exception:
Bad state: The client closed with pending request "initialize".
```

The simplified code is as follows. For context, the `mcp_server` requires a command line argument that is not supplied here.

```dart
import 'package:dart_mcp/client.dart';

void main() async {
  final client = MCPClient(
    ClientImplementation(name: 'example dart client', version: '0.1.0'),
  );
  print('connecting to server');
  final server = await client.connectStdioServer('dart', [
    'run',
    '../mcp_server/bin/mcp_server.dart',
  ]);
  print('server started');

  print('initializing server');
  final initializeResult = await server.initialize(
    InitializeRequest(
      protocolVersion: protocolVersion,
      capabilities: client.capabilities,
      clientInfo: client.implementation,
    ),
  );
  print('initialized: $initializeResult');
  if (initializeResult.protocolVersion != protocolVersion) {
    throw StateError(
      'Protocol version mismatch, expected $protocolVersion, '
      'got ${initializeResult.protocolVersion}',
    );
  }

  await client.shutdown();
}
```

The `pubspec.yaml` looks like the following:

```yaml
name: mcp_client
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  dart_mcp: ^0.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
```

Can we please add an exception or similar when the MCP server dies on initialization?
